### ISSUE TITLE
CTRL-Z in several source files

### ISSUE THREAD

**Issue by xecej4** [usda-ars-ussl/legacy#1]
Hi, several of the Fortran source files in the USDA-ars-ussl Github repository have CTRL-Z (ASCII 26, Hex 1A) characters at the end. Normally, this should not cause problems. 

See, for example, https://github.com/usda-ars-ussl/legacy/blob/master/src/SWMS_3D/SOURCE.FOR/TIME3.FOR . At the end you can see a rectangle with a question mark inside. That is a CTRL-Z.

However, if a user concatenates two or more source files for some reason, or uses some Fortran reformatting utility (for better readability, to add declarations, etc.), those CTRL-Zs can become very troublesome. Many current compilers ignore the rest of a source file when they encounter the CTRL-Z. This can cause make-files and the MAKE program to fail mysteriously in the link step. 

Please remove the CTRL-Zs from the source files. Thanks.

**Comment by thskaggs** [comment]
OK, done. Thanks.
